### ISSUE TITLE
asterisk_ex.py 예제 관련 질문입니다.

### ISSUE THREAD

**Issue by partrita** [TEAMLAB-Lecture/AI-python-connect#4]
AI-python-connect/codes/ch_1/pythonic_code/asterisk_ex.py

 에서 마지막 예제인 

```
def asterisk_test(a, b, c, d, e=0):
    print(a, b, c, d, e)


data = {"d":1 , "c":2, "b":3, "f"=56}
asterisk_test(10, **data)
```
에러가 나는데, 
 `"f"=56` 가 `"e":56`이 되어야 하는것 아닌가요?

**Comment by blissray** [comment]
This issue closed by the commit @28545a2.
